name: FIT4110_lab03_mock
values:
  - key: env
    value: mock
  - key: baseUrl
    value: 'http://localhost:4010'
  - key: authToken
    value: lab-token
  - key: teamName
    value: team-analytics
  - key: iotIngestionMockUrl
    value: 'http://localhost:4012'
  - key: aiVisionMockUrl
    value: 'http://localhost:4011'
  - key: tracePrefix
    value: fit4110-lab03
